project.yaml, schema.graphql, src/mappings/Transfers.ts, src/mappings/common.ts
=> Handle transfer_keep_alive

project.yaml, src/mappings/Rewards.ts, src/mappings/common.ts
Improve validator resolution algorithm for rewards. Now all cases are covered
Associate each reward with last seen validator from previous rewards in the block
Checked with https://polkadot.subscan.io/extrinsic/0x2db93338d71bb6822a2ce4e7d9c7cfd57589ae9d2cf3df70e5e579008d8e0415
=> Reward validators

project.yaml, schema.graphql, src/index.ts, src/mappings/NewEra.ts, src/mappings/NewSessions.ts
=> Store Stake data

project.yaml, schema.graphql, src/mappings/Rewards.ts, src/mappings/StakeChanged.ts
=> FLW-1022 Handle Unbonded | Slashed | Reward (restake) events for Analytics

src/mappings/Rewards.ts, src/mappings/common.ts, tsconfig.json
Example extrinsic https://polkadot.subscan.io/extrinsic/0x867065da698aaef1cf00e92f48cdcbeac133953c839468d246efeabc2913d35d
=> Handle Proxy.proxy call

schema.graphql, src/mappings/Rewards.ts
=> Skip "Reward/slash" events with errors

project.yaml, schema.graphql, src/mappings/NewEra.ts
```
{
query {
eraValidatorInfos(
filter:{
era:{greaterThanOrEqualTo:2579, lessThanOrEqualTo:2580},
others:{contains:[{who:"Dkt7txGAUX9Y4S4az8AgnUYSf6sGDqvwvQ87tVRfCma9xDr"}]}
}
) {
nodes {
id
address
era
total
own
others
}
}
}
}
```
**Result:**
```
{
"data": {
"query": {
"eraValidatorInfos": {
"nodes": [
{
"id": "8647092-3127HS3cSjc8QRMTZ4QzGytz5guoRnquj3w79qjsDryBpv4cc5x",
"address": "HS3cSjc8QRMTZ4QzGytz5guoRnquj3w79qjsDryBpv4cc5x",
"era": 2579,
"total": "4644924625772488",
"own": "10000000000",
"others": [
{
"who": "Dkt7txGAUX9Y4S4az8AgnUYSf6sGDqvwvQ87tVRfCma9xDr",
"value": "4644914625772488"
}
]
},
{
"id": "8647092-3274Gjq3WAFg7PCVaTtdV8qTHkFcvtJnTThcFo5gsFMqnuPqhCY",
"address": "Gjq3WAFg7PCVaTtdV8qTHkFcvtJnTThcFo5gsFMqnuPqhCY",
"era": 2579,
"total": "4644924625772488",
"own": …
```
=> Get Pending rewards filtered by eras range

schema.graphql, src/mappings/HistoryElements.ts, src/mappings/Transfers.ts
```
{
"timestamp": "1630287216",
"address": "HjeWhQQwMvr5j5PoY9vYQ7ZYfcL7pA2MDEhayxvVczXkuHb",
"transfer": {
"to": "HjeWhQQwMvr5j5PoY9vYQ7ZYfcL7pA2MDEhayxvVczXkuHb",
"fee": "10466570",
"from": "FXQWUgwp7NRYLgiy5nmDp3vuvtCFSfx1Fb2r5neXnL9orxP",
"block": "9000007",
"amount": "31611947667152",
"success": true,
"extrinsicId": "9000007-2"
}
},
{
"timestamp": "1630287234",
"address": "G7UkJAutjbQyZGRiP8z5bBSBPBJ66JbTKAkFDq3cANwENyX",
"transfer": {
"to": "EwJazuhLE5vvXu3pAn1YvZyNiMAWVywB1dLEaZCZZ2t3yMn",
"fee": "10533236",
"from": "G7UkJAutjbQyZGRiP8z5bBSBPBJ66JbTKAkFDq3cANwENyX",
"block": "9000010",
"amount": "3321000000000",
"success": true,
"extrinsicId": "9000010-2",
"extrinsicHash": "0x9cbb95ad505131107efb9a30db1c7e431e9233908ac1ab0a2d7cd9b6798d06c7"
}
}
```
=> Add extrinsicHash property to Transfer

schema.graphql, src/mappings/HistoryElements.ts, src/mappings/NewEra.ts, src/mappings/Rewards.ts, src/mappings/StakeChanged.ts, src/mappings/Transfers.ts, src/mappings/common.ts
=> Save block number, extrinsic index and extrinsic hash for HistoryElement

project.yaml, schema.graphql, src/mappings/Cache.ts, src/mappings/HistoryElements.ts, src/mappings/Rewards.ts, src/mappings/StakeChanged.ts, src/mappings/common.ts
- save rewards with payee address
- fix fee calculation typo
- add index to era and address of EraValidatorInfo
- make extrinsic id unique
=> Rewards and validators improvements

src/mappings/common.ts
- take into account both validator and treasury parts of fee
=> Fix fee calculation

schema.graphql, src/mappings/Rewards.ts
- improve rewards processing when reward for given account can be for nomination and validation in the same block
- add stash address to reward
=> Improve rewards handling

docker-compose.yml, project.yaml
Adding Docker await and changing naming
=> Fix polkadot sync error

schema.graphql, src/mappings/HistoryElements.ts, src/mappings/Transfers.ts, src/mappings/common.ts
[Custom asset transfer](https://app.clickup.com/t/2jpe0hj)
1. Add `assetTransfer` for history element
2. Fix failed transfers for custom assets
=> Custom asset transfer

networks/crab-solochain/chaintypes.ts, networks/crab-solochain/package.json, networks/crab-solochain/project.yaml
This PR adds crab-solochain to SubQuery project.
Was tested locally:
=> Adding crab-solochain

networks/nodle-solochain/chaintypes.ts, networks/nodle-solochain/project.yaml, networks/subsocial-solochain/package.json
This PR fixes problems with:
- nodle-solochain [indexer](https://project.subquery.network/project/nova-wallet/nova-wallet-nodle-solochain)
- subsocial-solochain [indexer](https://project.subquery.network/project/nova-wallet/nova-wallet-subsocial-solochain)
=> Fix for nodle-solochain and subsocial-solochain

networks/equilibrium/chaintypes.ts, networks/equilibrium/package.json, networks/equilibrium/project.yaml, networks/nodle-solochain/chaintypes.ts, networks/phala/package.json, networks/phala/project.yaml, networks/turing/package.json, networks/turing/project.yaml
This PR adds:
- New networks: Phala, Equilibrium, Turing
- Fix for typesBoundle for nodle-solochain
=> Adding new chains. Phala/Equilibrium/Turing

src/mappings/HistoryElements.ts, src/mappings/Transfers.ts, src/mappings/common.ts
https://app.clickup.com/t/2chjkyx
=> fix: fee calculation for evm transactions

networks/aleph-zero/chaintypes.ts, networks/aleph-zero/package.json, networks/aleph-zero/project.yaml
This PR adds new network for subquery project:
- Project was created - https://project.subquery.network/project/nova-wallet/nova-wallet-aleph-zero
- Types used from polkadot js - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/zero.ts
Indexer was tested for 1 block and 15_000_000 block:
<details>
<summary>from 1</summary>
</details>
<details>
<summary>from 15_000_000</summary>
</details>
=> Adding Aleph Zero network

networks/composable/package.json, networks/composable/project.yaml
This PR adds the Composable network
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcomposable-rpc.dwellir.com#/rpc
Was tested from 2 to 27007 blocks
<details>
<summary>Spoiler!</summary>
</details>
For some unknown reason it cannot index the first block.
=> Adding composable network

networks/polkadex/package.json, networks/polkadex/project.yaml
Adding polkadex network:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmainnet.polkadex.trade#/chainstate
=> Adding polkadex project

networks/altair/project.yaml, networks/astar/project.yaml, networks/basilisk/project.yaml, networks/bit-country/project.yaml, networks/calamari/project.yaml, networks/clover/project.yaml, networks/composable/project.yaml, networks/edgeware/project.yaml, networks/equilibrium/project.yaml, networks/hydra/project.yaml, networks/integritee-solochain/project.yaml, networks/integritee/project.yaml, networks/khala/project.yaml, networks/kico/project.yaml, networks/kilt/project.yaml, networks/moonbeam/project.yaml, networks/parallel-heiko/project.yaml, networks/parallel/project.yaml, networks/phala/project.yaml, networks/quartz/project.yaml, networks/shadow/project.yaml, networks/shiden/project.yaml, networks/statemint/project.yaml, networks/westmint/project.yaml
Was found that some networks haven't handler for custom assets
=> Fixed moonbeam for custom assets

networks/bifrost-polkadot/BifrostTypes.json, networks/bifrost-polkadot/package.json, networks/bifrost-polkadot/project.yaml, networks/dora/package.json, networks/dora/project.yaml, networks/litentry/package.json, networks/litentry/project.yaml, networks/origin-trail/package.json, networks/origin-trail/project.yaml, networks/unique/package.json, networks/unique/project.yaml
Adding new networks:
- OriginTrail
- Litentry
- UNIQUE
- Dora
=> Adding OriginTrail, Litentry, UNIQUE, Dora

networks/bajun/project.yaml, networks/shadow/project.yaml
This PR is fixing problems with
- Bajun network indexer (wrong genesis)
- Crust Shadow network indexer (wrong endpoint)
=> Fixing indexer's problems (Bajun, Crust Shadow)

scripts/python_scripts/generate_network_status.py
SubQuery API was updated and now we can get some instances of project in response.
This PR fix situation when we replace project by outdated
=> Fix for generate project statues script

networks/bifrost/project.yaml
Has tested by:
- [v1.4.0](https://hub.docker.com/layers/subql-query/onfinality/subql-query/v1.4.0/images/sha256-6d649c5796124a8b057c33b434eb19860fa65b6804bce39ff2b9376d9002cebb?context=explore)
- [v1.6.1](https://hub.docker.com/layers/subql-node/onfinality/subql-node/v1.6.1/images/sha256-921fcc27353148524d59b6a2c35fc6ff4f0eea1bb47b05f6e273f11f8547ec8c?context=explore)
=> Adding Bifrost parachain staking

.github/workflows/get_projects_status.yaml, scripts/python_scripts/generate_network_status.py
After updating all projects to the IPFS deploy system some project data were changed, that PR fixes script for update project statuses
=> Fix script for updating project statuses

.myriad-cid, myriad.yaml, package.json, yarn.lock
Adding Myriad network.
Tested  from blocks:
- 4764886
- 3476486
- 1
Project:
https://project.subquery.network/orgs/nova-wallet/projects/nova-wallet-myriad
=> Adding Myriad network

scripts/python_scripts/generate_network_status.py
This PR changes description for the project statuses table.
=> Change description for projects' statuses

amplitude.yaml, dao-ipci.yaml, ipfs-cids/.amplitude-cid, ipfs-cids/.dao-ipci-cid, ipfs-cids/.xx-network-cid, xx-network.yaml
Was run new subquery projects:
- [XX](https://project.subquery.network/orgs/nova-wallet/projects/nova-wallet-xx-network/deployments)
- [Amplitude](https://project.subquery.network/orgs/nova-wallet/projects/nova-wallet-amplitude/deployments)
- [DAO-IPCI](https://project.subquery.network/orgs/nova-wallet/projects/nova-wallet-dao-ipci/deployments)
=> Adding new projects. XX, Amplitude, DAO-IPCI

chainTypes/encointerChaintypes.ts, ipfs-cids/.encointer-cid
This PR fixed types for Encointer. Project is healthy:
https://managedservice.subquery.network/orgs/nova-wallet/projects/nova-wallet-encointer/deployments
=> fix Encointer types

bittensor.yaml, chainTypes/bittensorChaintypes.ts, ipfs-cids/.bittensor-cid, package.json
This PR adds Bittensor network, it is deployed here:
- https://managedservice.subquery.network/orgs/nova-wallet/projects/nova-wallet-bittensor/deployments
=> Adding Bittensor types

src/mappings/HistoryElements.ts
Tested on 1390654, where event 4 and extrinsic 4 were collided!
[test.log](https://github.com/novasamatech/subquery-nova/files/12301414/test.log)
=> add extrinsic suffix to avoid mixing extrinsic and event idxs

src/mappings/Cache.ts
correct extraction from StorageKey added
[test.log](https://github.com/novasamatech/subquery-nova/files/12513725/test.log)
=> Fixed addresses for pools

enjin-matrixchain.yaml, ipfs-cids/.enjin-matrixchain-cid
=> add enjin matrixchain project

src/mappings/common.ts
=> Prioritized estimated fee

src/mappings/Rewards.ts, src/mappings/common.ts
=> Fixed rewarded extension problems

scripts/python_scripts/generate_network_status.py
Temp remove telegram notifications
=> remove telegram notifications

ipfs-cids/.westend-cid, src/mappings/Rewards.ts
=> Implemented payoutStakersByPage logic

ipfs-cids/.mythos-cid, mythos.yaml
https://api.subquery.network/sq/nova-wallet/nova-wallet-mythos
=> adding mythos

src/mappings/Cache.ts
=> Fixed reward destination on runtime update(Reward event extended)

.github/workflows/docker.yml
Reverts novasamatech/subquery-history#311
=> Revert "bump to the 6.0.4 version"

statemine.yaml, statemint.yaml, westmint.yaml
https://github.com/novasamatech/nova-spektr/issues/4106
=> feat: add staking handlers for asset hubs
